# Generated by Django 2.2 on 2019-06-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='log_aws',
            field=models.TextField(null=True),
        ),
    ]
