# Generated by Django 2.2 on 2019-06-04 23:59
"""
MachineLearning for Early-Alert System project.

Created by Brayan Rojas, Elkin Prada, on June 2019.
Co-workers: Carlos Sierra, Santiago Salazar
Copyright (c) 2019 Brayan Rojas, Elkin Prada Corporación Universitaria Minuto de Dios. All rights reserved.

This file is part of ProjectName (BudRot-AutomaticDetection).

ProjectName (BudRot-AutomaticDetection) is free software: you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation, version 3.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='log_aws',
            field=models.TextField(null=True),
        ),
    ]
